---
- name: Install NFS client
  apt:
    name: nfs-common
    state: present

- name: Create mount points
  file:
    path: "{{ item.mount }}"
    state: directory
    mode: 0755
  loop:
    - { name: "data", mount: "/mnt/cluster-data" }    # Fixed path
    - { name: "backup", mount: "/mnt/cluster-backup" } # Fixed path

- name: Configure persistent mounts
  mount:
    path: "{{ item.mount }}"
    src: "{{ synology_ip | default('192.168.1.10') }}:{{ ( nfs_shares | default({'data':'/volume1/pi-cluster-data','backup':'/volume1/pi-cluster-backup'}) )[item.name] }}"
    fstype: nfs
    state: mounted
    opts: "defaults,_netdev"
  loop:
    - { name: "data", mount: "/mnt/cluster-data" }
    - { name: "backup", mount: "/mnt/cluster-backup" }
